### ISSUE TITLE
[RC5] Creation of nodes on scene every time the project is stopped due addon error

### ISSUE THREAD

**Issue by Cidragon** [AdrienQuillet/godot-yet-another-behavior-tree#25] opened 2023-02-27 01:00 UTC
**Steps to reproduce:**

- Start a scene with the addon enabled.
- Create any type of error that will make the addon stop the scene (like not assigning actor).
- Run the scene and wait for an error crash.
- Reload the project or close/open godot.

![Screenshot_20230226_215151](https://user-images.githubusercontent.com/23007679/221448701-dc30106c-fd57-40ca-b817-ebc59547560f.png)

Some additional info is that if you try to delete those nodes it will delete the original node that refer to

![Screenshot_20230226_215848](https://user-images.githubusercontent.com/23007679/221449242-c0802bad-0f0b-489f-a38e-f8c137cfcce1.png)

**Comment by Earewien** [comment] 2023-02-27 05:59
Seems to be related to https://github.com/godotengine/godot/issues/73905

This is a regression in Godot Engine that is already fixed. 

I will let this issue opened until RC 6. Can you try it when it's released ?

**Comment by Earewien** [comment] 2023-02-28 21:42
Fixed by RC6 👍

**Closed as completed by Earewien** 2023-02-28 21:42 UTC
